### ISSUE TITLE
Monitoring with grafana

### ISSUE THREAD

**Issue by kanchanm** [edwardsp/Azure-OnDemand#13]
Details of current support here: https://osc.github.io/ood-documentation/master/customization.html#grafana-support

**Comment by husiana** [comment]
So there are 2 ways :
First is to use Grafana along with InfluxDB as database and telegraf to collect data on compute nodes. This works well, but isn't integrated to OOD interface.
Second is to use Grafana along with Prometheus as database and plugins written in Go to collect data on compute nodes. This doesn't work - at all : Plugins in Go can't be installed on CentOS easily, you have to install Go, update (rebuild) Go with latest version before to collect anything. Then, prometheus integration is hardly usable, you need to redefine each new single compute node / remove them after from a yaml file + restart the prometheus daemon. It is supposed to be integrated with ood active jobs panel but I couldn't make it work.

I'm not a fan of go, neither rb so I'd keep a working scenario for now which consist of having a separate grafana dashboard from which you can collect every info you need in regards to the compute nodes.

**Comment by husiana** [comment]
Links for second option :
https://osc.github.io/ood-documentation/master/customization.html#grafana-support
https://grafana.com/grafana/dashboards/12093
https://www.fosslinux.com/10398/how-to-install-and-configure-prometheus-on-centos-7.htm
